### ISSUE TITLE
Great 500f6b5d32a9f108724e786db52095ac5769f05f commit

### ISSUE THREAD

**Issue by InigoEzcurdia** [ChristopherCastro/RSNG1516-TF#2]
I just wanted to congratulate you for your great job.

**Comment by carolbarce** [comment]
shut up and  kiss my ass. 1 to 0.  muajajajaja

**Comment by InigoEzcurdia** [comment]
Please don't be so rude. Respect your work mates.

**Comment by ChristopherCastro** [comment]
![803bb03d0948687903d839d6828472e479ba6234](https://cloud.githubusercontent.com/assets/749463/15742320/6aaea734-28be-11e6-8291-506abb401781.gif)
